### ISSUE TITLE
[Bug] node enviroment, `getImageBuffer` cause error

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VRender#70]
### Version

0.10.3

### Link to Minimal Reproduction

none

### Steps to Reproduce

run the following code in node environment:

```js
const fs = require('fs');

const VChart = require('@visactor/vchart');
const Canvas = require('..')
// const { container } = require('@visactor/vrender');
// const { nodeLoader } = require('@visactor/vrender-kits');

// // 加载node环境的loader
// nodeLoader(container);

// 正常的图表 spec 配置
const spec = {
  type: 'radar',
  data: [
    {
      id: '地图',
      values: [
        { key: '北', value: 31, category: '驱逐舰' },
        { key: '东北', value: 32, category: '驱逐舰' },
        { key: '东', value: 21, category: '驱逐舰' },
        { key: '东南', value: 15, category: '驱逐舰' },
        { key: '南', value: 50, category: '驱逐舰' },
        { key: '西南', value: 44, category: '驱逐舰' },
        { key: '西', value: 32, category: '驱逐舰' },
        { key: '西北', value: 32, category: '驱逐舰' },
        { key: '北', value: 31, category: '驱逐舰' },
        { key: '东北', value: 32, category: '驱逐舰' },
        { key: '东', value: 21, category: '驱逐舰' },
        { key: '东南', value: 40, category: '航母' },
        { key: '南', value: 25, category: '航母' },
        { key: '西南', value: 22, category: '航母' },
        { key: '西', value: 18, category: '航母' },
        { key: '西北', value: 7, category: '航母' },
        { key: '北', value: 24, category: '航母' },
        { key: '东北', value: 43, category: '航母' },
        { key: '东', value: 42, category: '航母' }
      ]
    }
  ],
  categoryField: 'key',
  valueField: 'value',
  seriesField: 'category',
  legends: {
    visible: true,
    orient: 'bottom'
  }
};
const cs = new VChart.default(spec, {
  // 声明使用的渲染环境以及传染对应的渲染环境参数
  mode: 'node',
  modeParams: Canvas,
  animation: false
});

cs.renderSync();

const buffer = cs.getImageBuffer();
fs.writeFileSync(`./chart.png`, buffer);
```

### Current Behavior

throw an error: 

```bash
Error: the surface type is not appropriate for the operation
    at qd.getImageBuffer (/Users/bytedance/temp/node-canvas/node_modules/@visactor/vrender/dist/index.js:1:429401)
    at t.DefaultWindow.getImageBuffer (/Users/bytedance/temp/node-canvas/node_modules/@visactor/vrender/dist/index.js:1:231945)
    at VChart.getImageBuffer (/Users/bytedance/temp/node-canvas/node_modules/@visactor/vchart/cjs/core/vchart.js:438:33)
    at Object.<anonymous> (/Users/bytedance/temp/node-canvas/examples/chart.js:57:19)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

### Expected Behavior

fix the bug.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by neuqzxy** [comment]
fixed in https://github.com/VisActor/VRender/pull/74
